- name: initiating connection on slave
  hosts: private[0]
  remote_user: ubuntu
  become: true

  tasks:
    - name: Giving nedded permissions to remoting dir
      ansible.builtin.file:
        path: /home/ubuntu/remoting/   
        owner: root
        group: root
        recurse: yes
        mode: '0777'

    - name: Create token file
      shell: echo d690c73565df156f3c7fd3330f065533cc5af1fc1f801951da3c139d8effb97d > secret-file

    - name: copy service file
      copy:
        src: /var/jenkins_home/workspace/terraform/scripts/slave.service
        dest: /etc/systemd/system/

    - name: reread systemd configs
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable connection service 
      ansible.builtin.systemd:
        state: started
        name: slave.service
        enabled: yes
    