- name: initiating connection on slave
  hosts: private[0]
  remote_user: ubuntu
  become: true

  tasks:
    - name: Giving nedded permissions to remoting dir
      ansible.builtin.file:
        path: /home/ubuntu/remoting/   
        owner: root
        group: root
        recurse: yes
        mode: '0777'

    - name: copy agent secret file
      copy:
        src: ~/secrets/secret-file
        dest: /home/ubuntu
        
    - name: copy service file
      copy:
        src: ../scripts/slave.service
        dest: /etc/systemd/system/

    - name: reread systemd configs
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable connection service 
      ansible.builtin.systemd:
        state: started
        name: slave.service
        enabled: yes
    