- name: confiure Slave Node
  hosts: private[0]
  remote_user: ubuntu
  become: true
  tasks:
    - name: update cache
      apt: update_cache=yes

    - name: install default-jre
      apt:
        name: default-jre
        state: present 
    
    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: adding user to docker group
      user:
        name: "ubuntu"
        groups: docker
        append: yes
    
    - name: download agent.jar file 
      get_url:
        url: http://35.216.139.94/jnlpJars/agent.jar
        dest: /home/ubuntu
    
    - name: copy .env file
      copy:
        src: /var/jenkins_home/workspace/terraform/provisioner/.env
        dest: /home/ubuntu

    - name: initiating connection
      shell: "java -jar agent.jar -jnlpUrl http://35.216.139.94/computer/private/jenkins-agent.jnlp -secret 966ad760b20b4af01f15878db892ecc46bec26b3d4e673abb975514c4f5078e7 -workDir /home/ubuntu &"
 
