- name: confiure Slave Node
  hosts: private
  remote_user: ubuntu
  become: true
  tasks:
    - name: update cache
      apt: update_cache=yes

    - name: install default-jre
      apt:
        name: default-jre
        state: present 
    
    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: adding user to docker group
      user:
        name: "ubuntu"
        groups: docker
        append: yes
    
    - name: confiure node as agent
      debug:
        msg: "java -jar agent.jar -jnlpUrl http://34.89.42.194/computer/private%2Dslave/jenkins-agent.jnlp -secret bb9589a1a8f6d2b3942629d6dbf4016853d80f8d38eca8a61d84102c688fbb7c -workDir \"/home/ubuntu\""